0.3.26

diff --git a/lib/bin/dist-upgrade b/lib/bin/dist-upgrade
--- a/lib/bin/dist-upgrade
+++ b/lib/bin/dist-upgrade
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# Last update 2018/03/29
+
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus"
 if [ "`cat /etc/default/locale | grep de_DE`" != "" ]; then
@@ -27,7 +29,6 @@ else
 fi
 
 testroot="`whoami`"
-
 if [ "$testroot" != "root" ]; then
 	/usr/bin/remsu $0 &
 fi
@@ -37,11 +38,11 @@ TITLE="--always-print-result --dialog-sep --image=system-software-install --titl
 TEXT="--text="
 MSGBOX=" --button=Ok:0"
 TITLETEXT="APTus"
-
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 # check connection
@@ -52,7 +53,7 @@ if [ "$PINGTEST" = "" ]; then
 	exit 1
 fi
 
-$SPARKYXTERM -e "apt-get dist-upgrade"
+$SPARKYXTERM "apt-get dist-upgrade"
 
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL8"
 
diff --git a/lib/bin/fix-dpkg b/lib/bin/fix-dpkg
--- a/lib/bin/fix-dpkg
+++ b/lib/bin/fix-dpkg
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# Last update 2018/03/29
+
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus"
 if [ "`cat /etc/default/locale | grep de_DE`" != "" ]; then
@@ -36,14 +38,14 @@ TITLE="--always-print-result --dialog-sep --image=system-software-install --titl
 TEXT="--text="
 MSGBOX=" --button=Ok:0"
 TITLETEXT="APTus"
-
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
-$SPARKYXTERM -e "dpkg --configure -a"
+$SPARKYXTERM "dpkg --configure -a"
 
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL8"
 
diff --git a/lib/bin/install-deb b/lib/bin/install-deb
--- a/lib/bin/install-deb
+++ b/lib/bin/install-deb
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-#  Last update 2018/03/16 by pavroo
+# Last update 2018/03/29 by pavroo
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus"
@@ -41,11 +41,11 @@ FILESELECTION="--file-selection "
 FILTER="--file-filter"
 MSGBOX="--button=Ok:0"
 TITLETEXT="APTus"
-
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 # check connection
@@ -63,8 +63,10 @@ if [ "$?" != "0" ]; then
 	exit 0
 
 else
-	$SPARKYXTERM -e "gdebi $DEBFILE"
+	$SPARKYXTERM "gdebi $DEBFILE"
 
 	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL8"
 	exit 0
 fi
+
+exit 0
diff --git a/lib/bin/install-debian-kernel b/lib/bin/install-debian-kernel
--- a/lib/bin/install-debian-kernel
+++ b/lib/bin/install-debian-kernel
@@ -1,11 +1,10 @@
 #!/bin/bash
 
 # install-debian-kernel script lets you install the default Debian's Linux kernel
-#
 # Copyright 2018 Paweł "pavroo" Pijanowski <pavroo@onet.eu>
 # Licensed under the GPLv2 license see /usr/share/common-licenses/GPL-2
 # Created 2018/02/18
-# Last update 2018/03/16
+# Last update 2018/03/29
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus"
@@ -49,10 +48,11 @@ ARCH=`uname -r | grep "amd64"`
 TESTDEBIAN64=`dpkg-query -l | grep linux-image-amd64`
 TESTDEBIAN32=`dpkg-query -l | grep linux-image-686 | grep -v pae`
 TESTDEBIAN32PAE=`dpkg-query -l | grep linux-image-686-pae`
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 # check connection
@@ -109,12 +109,11 @@ if [ "$TESTDEBIAN32" != "" ]; then
 fi
 
 # install i686 NON-PAE Debian kernel and headers
-$SPARKYXTERM -e "apt-get update && apt-get install linux-image-686 linux-headers-686"
+$SPARKYXTERM "apt-get update"
+$SPARKYXTERM "apt-get install linux-image-686 linux-headers-686"
 
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL75"
-
 exit 0
-
 }
 
 paemenu () {
@@ -130,12 +129,11 @@ if [ "$TESTDEBIAN32PAE" != "" ]; then
 fi
 
 # install i686 PAE Debian kernel and headers
-$SPARKYXTERM -e "apt-get update && apt-get install linux-image-686-pae linux-headers-686-pae"
+$SPARKYXTERM "apt-get update"
+$SPARKYXTERM "apt-get install linux-image-686-pae linux-headers-686-pae"
 
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL75"
-
 exit 0
-
 }
 
 amd64menu () {
@@ -151,12 +149,11 @@ if [ "$TESTDEBIAN64" != "" ]; then
 fi
 
 # install 64 bit Debian kernel and headers
-$SPARKYXTERM -e "apt-get update && apt-get install linux-image-amd64 linux-headers-amd64"
+$SPARKYXTERM "apt-get update"
+$SPARKYXTERM "apt-get install linux-image-amd64 linux-headers-amd64"
 
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL75"
-
 exit 0
-
 }
 
 mainmenu
diff --git a/lib/bin/install-liquorix b/lib/bin/install-liquorix
--- a/lib/bin/install-liquorix
+++ b/lib/bin/install-liquorix
@@ -1,11 +1,10 @@
 #!/bin/bash
 
 # install-liquorix script lets you install the 3th party Liquorix Linux kernel
-#
 # Copyright 2015-2018 Paweł "pavroo" Pijanowski <pavroo@onet.eu>
 # Licensed under the GPLv2 license see /usr/share/common-licenses/GPL-2
 # Created 2015/05/18
-# Last update 2018/03/16
+# Last update 2018/03/29
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus"
@@ -34,7 +33,6 @@ else
 fi
 
 testroot="`whoami`"
-
 if [ "$testroot" != "root" ]; then
 	/usr/bin/remsu $0 &
 fi
@@ -48,10 +46,11 @@ MSGBOX="--button=Ok:0"
 TITLETEXT="$LOCAL23"
 ARCH=`uname -r | grep "amd64" | awk '{print $1}'`
 TESTLIQ=`dpkg-query -l | grep linux-image-liquorix*`
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 # check is the Liquorix kernel installed already
@@ -89,64 +88,47 @@ else
 fi
 
 if [ "$CHOICE" = "NON_PAE" ]; then
-nonpaemenu
+	nonpaemenu
 elif [ "$CHOICE" = "PAE" ]; then
-paemenu
+	paemenu
 elif [ "$CHOICE" = "64" ]; then
-64menu
+	amd64menu
 elif [ "$CHOICE" = "Exit" ]; then
-exit 0
+	exit 1
 else
-exit 0
+	exit 1
 fi
 }
 
 nonpaemenu () {
 if [ "$ARCH" != "" ]; then
-$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL31"
-mainmenu
+	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL31"
+	mainmenu
 fi
 
 # check the Liquorix list
-if [ ! -f /etc/apt/sources.list.d/liquorix.list ]; then
+if [ -f /etc/apt/sources.list.d/liquorix.list ]; then
+	rm -f /etc/apt/sources.list.d/liquorix.list
+fi
+
+# create new list
 cat > /etc/apt/sources.list.d/liquorix.list <<FOO
 # Liquorix kernel
 deb http://liquorix.net/debian sid main
 deb-src http://liquorix.net/debian sid main
-
 FOO
 
 # install Liquorix keyring
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install apt-transport-https -y --force-yes"
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install liquorix-keyring -y --force-yes"
-
-else
-
-rm -f /etc/apt/sources.list.d/liquorix.list
-
-cat > /etc/apt/sources.list.d/liquorix.list <<FOO
-# Liquorix kernel
-deb http://liquorix.net/debian sid main
-deb-src http://liquorix.net/debian sid main
-
-FOO
-
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install apt-transport-https -y --force-yes"
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install liquorix-keyring -y --force-yes"
-
-fi
+$SPARKYXTERM "apt-get update"
+$SPARKYXTERM "apt-get install apt-transport-https -y --force-yes"
+$SPARKYXTERM "apt-get update"
+$SPARKYXTERM "apt-get install liquorix-keyring -y --force-yes"
 
 # install i686 NON-PAE Liquorix kernel
-$SPARKYXTERM -e "apt-get install linux-image-liquorix-686 linux-headers-liquorix-686"
+$SPARKYXTERM "apt-get install linux-image-liquorix-686 linux-headers-liquorix-686"
 
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL32"
-
 exit 0
-
 }
 
 paemenu () {
@@ -156,93 +138,59 @@ mainmenu
 fi
 
 # check the Liquorix list
-if [ ! -f /etc/apt/sources.list.d/liquorix.list ]; then
+if [ -f /etc/apt/sources.list.d/liquorix.list ]; then
+	rm -f /etc/apt/sources.list.d/liquorix.list
+fi
+
+# create new list
 cat > /etc/apt/sources.list.d/liquorix.list <<FOO
 # Liquorix kernel
 deb http://liquorix.net/debian sid main
 deb-src http://liquorix.net/debian sid main
-
 FOO
 
 # install Liquorix keyring
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install apt-transport-https -y --force-yes"
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install liquorix-keyring -y --force-yes"
-
-else
-
-rm -f /etc/apt/sources.list.d/liquorix.list
-
-cat > /etc/apt/sources.list.d/liquorix.list <<FOO
-# Liquorix kernel
-deb http://liquorix.net/debian sid main
-deb-src http://liquorix.net/debian sid main
-
-FOO
-
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install apt-transport-https -y --force-yes"
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install liquorix-keyring -y --force-yes"
-
-fi
+$SPARKYXTERM "apt-get update"
+$SPARKYXTERM "apt-get install apt-transport-https -y --force-yes"
+$SPARKYXTERM "apt-get update"
+$SPARKYXTERM "apt-get install liquorix-keyring -y --force-yes"
 
 # install i686 PAE Liquorix kernel
-$SPARKYXTERM -e "apt-get install linux-image-liquorix-686-pae linux-headers-liquorix-686-pae"
+$SPARKYXTERM "apt-get install linux-image-liquorix-686-pae linux-headers-liquorix-686-pae"
 
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL32"
-
 exit 0
-
 }
 
-64menu () {
+amd64menu () {
 if [ "$ARCH" = "" ]; then
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL33"
 mainmenu
 fi
 
 # check the Liquorix list
-if [ ! -f /etc/apt/sources.list.d/liquorix.list ]; then
+if [ -f /etc/apt/sources.list.d/liquorix.list ]; then
+	rm -f /etc/apt/sources.list.d/liquorix.list
+fi
+
+# create new list
 cat > /etc/apt/sources.list.d/liquorix.list <<FOO
 # Liquorix kernel
 deb http://liquorix.net/debian sid main
 deb-src http://liquorix.net/debian sid main
-
 FOO
 
 # install Liquorix keyring
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install apt-transport-https -y --force-yes"
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install liquorix-keyring -y --force-yes"
-
-else
-
-rm -f /etc/apt/sources.list.d/liquorix.list
-
-cat > /etc/apt/sources.list.d/liquorix.list <<FOO
-# Liquorix kernel
-deb http://liquorix.net/debian sid main
-deb-src http://liquorix.net/debian sid main
-
-FOO
-
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install apt-transport-https -y --force-yes"
-$SPARKYXTERM -e "apt-get update"
-$SPARKYXTERM -e "apt-get install liquorix-keyring -y --force-yes"
-
-fi
+$SPARKYXTERM "apt-get update"
+$SPARKYXTERM "apt-get install apt-transport-https -y --force-yes"
+$SPARKYXTERM "apt-get update"
+$SPARKYXTERM "apt-get install liquorix-keyring -y --force-yes"
 
 # install 64 bit Liquorix kernel
-$SPARKYXTERM -e "apt-get install linux-image-liquorix-amd64 linux-headers-liquorix-amd64"
+$SPARKYXTERM "apt-get install linux-image-liquorix-amd64 linux-headers-liquorix-amd64"
 
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL32"
-
 exit 0
-
 }
 
 mainmenu
diff --git a/lib/bin/install-sparky-kernel b/lib/bin/install-sparky-kernel
--- a/lib/bin/install-sparky-kernel
+++ b/lib/bin/install-sparky-kernel
@@ -5,7 +5,7 @@
 # Copyright 2016 Paweł "pavroo" Pijanowski <pavroo@onet.eu>
 # Licensed under the GPLv2 license see /usr/share/common-licenses/GPL-2
 # Created 2016/04/06
-# Last update 2018/03/16
+# Last update 2018/03/29
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus"
@@ -47,10 +47,11 @@ MSGBOX="--button=Ok:0"
 TITLETEXT="$LOCAL60"
 ARCH=`uname -r | grep "amd64" | awk '{print $1}'`
 TESTSPARKY=`dpkg-query -l | grep linux-image-sparky*`
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 # check is the Sparky kernel installed already
@@ -117,15 +118,13 @@ deb http://sparkylinux.org/repo/ unstable main
 deb-src http://sparkylinux.org/repo/ unstable main
 FOO
 
-$SPARKYXTERM -e "apt-get update"
+$SPARKYXTERM "apt-get update"
 
 # install i686 NON-PAE Sparky kernel and headers
-$SPARKYXTERM -e "apt-get install linux-image-sparky-686 linux-headers-sparky-686"
+$SPARKYXTERM "apt-get install linux-image-sparky-686 linux-headers-sparky-686"
 
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL65"
-
 exit 0
-
 }
 
 paemenu () {
@@ -145,15 +144,13 @@ deb http://sparkylinux.org/repo/ unstable main
 deb-src http://sparkylinux.org/repo/ unstable main
 FOO
 
-$SPARKYXTERM -e "apt-get update"
+$SPARKYXTERM "apt-get update"
 
 # install i686 PAE Sparky kernel and headers
-$SPARKYXTERM -e "apt-get install linux-image-sparky-686-pae linux-headers-sparky-686-pae"
+$SPARKYXTERM "apt-get install linux-image-sparky-686-pae linux-headers-sparky-686-pae"
 
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL65"
-
 exit 0
-
 }
 
 amd64menu () {
@@ -173,15 +170,13 @@ deb http://sparkylinux.org/repo/ unstable main
 deb-src http://sparkylinux.org/repo/ unstable main
 FOO
 
-$SPARKYXTERM -e "apt-get update"
+$SPARKYXTERM "apt-get update"
 
 # install 64 bit Sparky kernel and headers
-$SPARKYXTERM -e "apt-get install linux-image-sparky-amd64 linux-headers-sparky-amd64"
+$SPARKYXTERM "apt-get install linux-image-sparky-amd64 linux-headers-sparky-amd64"
 
 $DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL65"
-
 exit 0
-
 }
 
 mainmenu
diff --git a/lib/bin/nonfree-remove b/lib/bin/nonfree-remove
--- a/lib/bin/nonfree-remove
+++ b/lib/bin/nonfree-remove
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# Last update 2018/03/29
+
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus"
 if [ "`cat /etc/default/locale | grep de_DE`" != "" ]; then
@@ -38,10 +40,11 @@ TEXT="--text="
 OKEXIT="--button=Ok:0 --button=$LOCAL24:1"
 MSGBOX="--button=Ok:0"
 TITLETEXT="APTus"
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 NONFREE=`vrms -s | cut -d "|" -f 1`
@@ -49,14 +52,13 @@ NONFREE=`vrms -s | cut -d "|" -f 1`
 $DIALOG500 $TITLE"$LOCAL34" $OKEXIT $TEXT"$LOCAL35:\n\n$NONFREE \n\n$LOCAL36"
 
 if [ "$?" != "0" ]; then
-
 	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL37"
 	exit 0
-
 else
-
-	$SPARKYXTERM -e "apt-get remove $NONFREE"
+	$SPARKYXTERM "apt-get remove $NONFREE"
 
 	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL8"
 	exit 0
 fi
+
+exit 0
diff --git a/lib/bin/old-kernel-remover b/lib/bin/old-kernel-remover
--- a/lib/bin/old-kernel-remover
+++ b/lib/bin/old-kernel-remover
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # old-kernel-remover by pavroo <pavroo@onet.eu>
-# last update 2018/03/16
+# last update 2018/03/29
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus"
@@ -31,7 +31,7 @@ fi
 
 testroot="`whoami`"
 if [ "$testroot" != "root" ]; then
-	echo "Must be root...Exiting now..."
+	echo "Must be root... Exiting now..."
 	exit 1
 fi
 
@@ -43,11 +43,11 @@ OKEXIT="--button=Ok:0 --button=$LOCAL24:1"
 MSGBOX="--button=Ok:0"
 TITLETEXT="$LOCAL69"
 MENU="--list --column=No --column=Kernel"
-
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 if [ -d /tmp/old-kernel-remover ]; then
@@ -248,7 +248,9 @@ if [ "$REMOVEKERNEL" != "" ]; then
 		exit 0
 	else
 		# remove kernel and headers now
-		$SPARKYXTERM -e "apt-get purge $REMOVEKERNEL --yes && apt-get purge $REMOVEHEADERS --yes && apt-get autoremove"
+		$SPARKYXTERM "apt-get purge $REMOVEKERNEL -y"
+		$SPARKYXTERM "apt-get purge $REMOVEHEADERS -y"
+		$SPARKYXTERM "apt-get autoremove"
 		
 		$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"\n$LOCAL8"
 		exit 0
diff --git a/lib/bin/quick-install b/lib/bin/quick-install
--- a/lib/bin/quick-install
+++ b/lib/bin/quick-install
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# Last update 2018/03/29
+
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus"
 if [ "`cat /etc/default/locale | grep de_DE`" != "" ]; then
@@ -40,11 +42,11 @@ ENTRY="--entry "
 ENTRYTEXT="--entry-text "
 MSGBOX="--button=Ok:0"
 TITLETEXT="APTus"
-
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 # check connection
@@ -60,11 +62,11 @@ PACK1=`$DIALOG450 $TITLE"$LOCAL44" $OKEXIT $ENTRY $TEXT"$LOCAL45"`
 if [ "$?" != "0" ]; then
 	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL12"
 	exit 0
-
 else
-	$SPARKYXTERM -e "apt-get install $PACK1"
+	$SPARKYXTERM "apt-get install $PACK1"
 
 	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL8"
 	exit 0
 fi
+
 exit 0
diff --git a/lib/bin/vboxguest-remove b/lib/bin/vboxguest-remove
--- a/lib/bin/vboxguest-remove
+++ b/lib/bin/vboxguest-remove
@@ -7,7 +7,7 @@
 # Copyright 2015-2018 Paweł "pavroo" Pijanowski <pavroo@onet.eu>
 # Licensed under the GPLv2 license see /usr/share/common-licenses/GPL-2
 # Created 2015/05/18
-# Last update 2018/03/16
+# Last update 2018/03/29
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus"
@@ -47,11 +47,11 @@ TEXT="--text="
 OKEXIT=" --button=Ok:0 --button=$LOCAL24:1"
 MSGBOX="--button=Ok:0"
 TITLETEXT="$LOCAL54"
-
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 if [ ! -f /usr/sbin/VBoxControl ]; then
@@ -62,24 +62,20 @@ fi
 $DIALOG400 $TITLE"$TITLETEXT" $OKEXIT $TEXT"$LOCAL56"
 
 if [ "$?" != "0" ]; then
-
 	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL37"
-	exit 0
-
+	exit 1
 else
-
-	$SPARKYXTERM -e "apt-get remove virtualbox-guest-utils -y"
-	$SPARKYXTERM -e "apt-get autoremove -y"
+	$SPARKYXTERM "apt-get remove virtualbox-guest-utils -y"
+	$SPARKYXTERM "apt-get autoremove -y"
 fi
 
 # check has the package been removed
 if [ -f /usr/sbin/VBoxControl ]; then
 	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL57"
 	exit 0
-
 else
 	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL8"
 	exit 0
-
 fi
+
 exit 0
